// Code generated by swaggo/swag. DO NOT EDIT.

package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/auth/login": {
            "post": {
                "tags": [
                    "auth"
                ],
                "summary": "Принимает данные пользователя для входа в систему",
                "operationId": "login",
                "parameters": [
                    {
                        "description": "Данные для логина",
                        "name": "user_credentials",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/fixtures.LoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/fixtures.LoginResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/app_errors.AppError"
                        }
                    }
                }
            }
        },
        "/auth/register": {
            "post": {
                "tags": [
                    "auth"
                ],
                "summary": "Принимает данные пользователя",
                "operationId": "register",
                "parameters": [
                    {
                        "description": "Данные для регистрации",
                        "name": "user_data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/fixtures.RegisterRequest"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/app_errors.AppError"
                        }
                    }
                }
            }
        },
        "/face_model/save_features": {
            "post": {
                "tags": [
                    "Save CSV"
                ],
                "summary": "Принимает csv файл с фичами из видео",
                "operationId": "save csv",
                "parameters": [
                    {
                        "type": "file",
                        "description": "Загружаемый csv",
                        "name": "file",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/app_errors.AppError"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "app_errors.AppError": {
            "type": "object",
            "required": [
                "code",
                "message",
                "name",
                "status"
            ],
            "properties": {
                "code": {
                    "description": "Код ошибки",
                    "type": "integer",
                    "example": 26002
                },
                "message": {
                    "description": "Сообщение ошибки",
                    "type": "string",
                    "example": "entity not found"
                },
                "name": {
                    "description": "Наименование ошибки",
                    "type": "string",
                    "example": "NotFound"
                },
                "status": {
                    "description": "Статус код ответа",
                    "type": "integer",
                    "example": 404
                }
            }
        },
        "fixtures.LoginRequest": {
            "type": "object",
            "required": [
                "login",
                "password"
            ],
            "properties": {
                "login": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "fixtures.LoginResponse": {
            "type": "object",
            "properties": {
                "get_face_model_url": {
                    "type": "string"
                },
                "upload_face_model_features_url": {
                    "type": "string"
                }
            }
        },
        "fixtures.RegisterRequest": {
            "type": "object",
            "required": [
                "login",
                "password"
            ],
            "properties": {
                "login": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "surname": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/api/v1/",
	Schemes:          []string{},
	Title:            "User data service API",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
