version: "3.5"

services:
  postgres:
    container_name: postgres
    image: postgres:15.2
    environment:
      POSTGRES_DB: $DB_NAME
      POSTGRES_USER: $DB_USERNAME
      POSTGRES_PASSWORD: $DB_PASSWORD
    ports:
      - $EXPOSE_DB_PORT:$DB_PORT
    volumes:
      - ./data:/var/lib/postgresql/data
  rabbitmq:
    container_name: rabbitmq-convert-service
    image: rabbitmq:3.8-management
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
    ports:
      - "5672:5672"
      - "15672:15672"

volumes:
  data: