version: "3.5"

services:
  postgres:
    container_name: postgres
    image: postgres:15.2
    environment:
      POSTGRES_DB: $DB_NAME
      POSTGRES_USER: $DB_USERNAME
      POSTGRES_PASSWORD: $DB_PASSWORD
    ports:
      - $EXPOSE_DB_PORT:$DB_PORT
    volumes:
      - ./data:/var/lib/postgresql/data

volumes:
  data: