version: "3.5"

services:
  model-handler-ps:
    image: postgres:15.2
    environment:
      POSTGRES_DB: 'debug'
      POSTGRES_USER:  'debug'
      POSTGRES_PASSWORD:  'debug'
    ports:
      - '5436:5432'

  features-storage-ps:
    image: postgres:15.2
    environment:
      POSTGRES_DB: 'debug'
      POSTGRES_USER: 'debug'
      POSTGRES_PASSWORD: 'debug'
    ports:
      - '5437:5432'

  user-data-ps:
    image: postgres:15.2
    environment:
      POSTGRES_DB: 'debug'
      POSTGRES_USER: 'debug'
      POSTGRES_PASSWORD: 'debug'
    ports:
      - '5438:5432'

  minio:
    image: minio/minio
    ports:
      - '9000:9000'
      - '9001:9001'
    environment:
      MINIO_ROOT_USER: $MINIO_ROOT_USER
      MINIO_ROOT_PASSWORD: $MINIO_ROOT_PASSWORD
    volumes:
      - 'minio_data:/data'
    command: server --console-address ":9001" /data

  rabbitmq:
    container_name: rabbitmq-convert-service
    image: rabbitmq:3.10.7-management
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
    ports:
      - "5672:5672"
      - "15672:15672"

volumes:
  minio_data:
    driver: local