version: "3.5"

services:
  postgres:
    image: postgres:15.2
    environment:
      POSTGRES_DB: $DB_NAME
      POSTGRES_USER: $DB_USERNAME
      POSTGRES_PASSWORD: $DB_PASSWORD
    ports:
      - $EXPOSE_DB_PORT:$DB_PORT

  minio:
    image: minio/minio
    ports:
      - '9000:9000'
      - '9001:9001'
    environment:
      MINIO_ROOT_USER: $MINIO_ROOT_USER
      MINIO_ROOT_PASSWORD: $MINIO_ROOT_PASSWORD
    volumes:
      - 'minio_data:/data'
    command: server --console-address ":9001" /data

volumes:
  minio_data:
    driver: local